<?php
$cars = [
    [
        'id' => '1',
        'marca' => 'renault',
        'modello' => 'captur',
        'targa' => 'FB 123 CD',
        'anno' => 2016,
        'cilindrata' => 1500,
        'carburante' => 'diesel',
        'versione' => 'base',
        'telaio' => 'abc1234efghil5678',
        'porte' => 5,
        'posti' => 5,
        'chilometri' => 21000,
        'proprietari' => 'null',
        'tagliandi' => '12/06/2017 passato',
        'revisioni' => '11/11/2018 passata',
        'colore' => 'grigio',
        'immagine' => 'https://cdn.miacar.it/thumbs/vehicle-gallery-800x560/cars/RENAULT/CAPTUR/tce-12v-100-cv-zen/grigio-magnete/3k0b3k3/a.JPG',
        'prezzo' => 11900.00,
    ],
    [
        'id' => '2',
        'marca' => 'fiat',
        'modello' => 'panda',
        'targa' => 'cz 456 rd',
        'anno' => 2010,
        'cilindrata' => 1200,
        'carburante' => 'benzina',
        'versione' => 'base',
        'telaio' => 'bdc1734evvhil5118',
        'porte' => 5,
        'posti' => 4,
        'chilometri' => 102000,
        'proprietari' => 'Carlo Cracco',
        'tagliandi' => '22/06/2013 passato, 14/08/2016 passato, 02/02/2019 passato',
        'revisioni' => '11/11/2018 passata',
        'colore' => 'giallo',
        'immagine' => 'null',
        'prezzo' => 6900.00,
    ],
    [
        'id' => '3',
        'marca' => 'mercedes',
        'modello' => 'classe a',
        'targa' => 'fa 121 gh',
        'anno' => 2020,
        'cilindrata' => 1900,
        'carburante' => 'benzina',
        'versione' => 'sport',
        'telaio' => 'zdc4738ejlhil7538',
        'porte' => 5,
        'posti' => 5,
        'chilometri' => 19000,
        'proprietari' => 'Steve Jobs',
        'tagliandi' => '02/02/2022 passato',
        'revisioni' => 'null',
        'colore' => 'nero',
        'immagine' => 'null',
        'prezzo' => 19900.00,
    ],
]
?>